services:
  - type: worker
    name: pdf-ai-slides-bot
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: CHANNEL_USER
        value: "@xonziyy"
